### PR TITLE
Added some capitalization and punctuation

### PR DESCRIPTION
**Pull request by Ryan-McBride**

### CODE REVIEW

**Comment by toish** [comment]
Full stop feels a little bland, maybe an ‽ might be better?

**Comment by Ryan-McBride** [comment]
Interrobang doesn't make much sense in the context of this sentence. I will however add an ellipsis so that it trails off intriguingly...

**Comment by toish** [comment]
I'm feeling it, make it happen

**Comment by Ryan-McBride** [comment]
Opened  pull request #3 for this.

**Pull request closed without merging**
